export const work = [
  {
    slug: 'city-green-solutions',
    company: 'City Green Solutions',
    location: 'Victoria, BC',
    period: 'Jul 2023 – Dec 2025',
    type: 'Full-Time',
    role: 'Marketing & Customer Experience Specialist',
    description:
      'At City Green Solutions I owned the full marketing function for a government-funded home energy retrofit program — from strategy through execution. The work spanned lifecycle email campaigns, paid social, event marketing, and CRM-driven audience segmentation across five municipal districts in British Columbia. The biggest challenge was low program participation despite active outreach: residents weren\'t engaging because messaging wasn\'t tailored to their stage or eligibility. I rebuilt the communication architecture in HubSpot, segmented audiences by behaviour and eligibility, and designed drip sequences for every stage of the funnel. I also conceived and produced the Retrofit Community Festival — an annual event connecting homeowners with certified contractors — which became the program\'s highest-engagement channel.',
    stats: [
      { value: '↑25–35%', label: 'Program Engagement' },
      { value: '↓20%',    label: 'Drop-off Rate'       },
      { value: '↑15%',    label: 'Email Engagement'    },
    ],
    bullets: [
      'Planned and executed multi-channel lifecycle campaigns across email, social, and web — contributing to a 25–35% increase in program engagement.',
      'Developed and optimised customer journey touchpoints reducing user drop-offs by 20% across Instagram, LinkedIn, and YouTube.',
      'Managed CRM-driven communications via HubSpot, segmenting audiences for targeted messaging based on user behaviour and program eligibility.',
      'Designed and conducted market research and surveys for 5 municipal districts across British Columbia.',
      'Designed, branded, and executed the Retrofit Community Festival — an annual event connecting homeowners with certified contractors.',
      'Built GA4 dashboards and ran A/B tests to refine messaging, boosting engagement rates by 15%.',
    ],
    tools: ['HubSpot', 'GA4', 'Email Marketing', 'Meta Ads', 'Google Ads', 'A/B Testing', 'Event Marketing', 'Market Research'],
    artifacts: [
      { type: 'image', src: '/artifacts/city-green-solutions/home-energy-CRD.png',      caption: 'Home Energy CRD' },
      { type: 'image', src: '/artifacts/city-green-solutions/home-energy-kelowna.png',   caption: 'Home Energy Kelowna' },
      { type: 'image', src: '/artifacts/city-green-solutions/home-energy-kelowna2.png',  caption: 'Home Energy Kelowna 2' },
      { type: 'image', src: '/artifacts/city-green-solutions/home-energy-kelowna3.jpg',  caption: 'Home Energy Kelowna 3' },
      { type: 'pdf', driveId: '1tqY5T4ycQtsdZ8d9QLTQKpU1Dj3bnPnv', caption: 'Richmond home energy' },
      { type: 'pdf', driveId: '1gBP2LiV8N7VlNfpvynB8HZPlXHAtEcwu', caption: 'Retrofit community festival' },
    ],
  },
  {
    slug: 'her-helping-habit',
    company: 'Her Helping Habit',
    location: 'Vancouver, BC',
    period: 'Feb 2023 – Jul 2023',
    type: 'Contract',
    role: 'Marketing Lead',
    description:
      'Her Helping Habit is a women\'s wellness brand with a growing international audience. I joined as Marketing Lead to take the brand from a single-market operation to a multi-country presence — on a limited budget and without local teams on the ground. I audited every paid channel from scratch, identified where budget was being wasted, and rebuilt acquisition campaigns with structured A/B testing and tighter audience segmentation. Alongside performance work, I relaunched the Fertility Frontier podcast and led a small content team producing web, social, and audio output. The international expansion — Mexico, Finland, Australia — was validated market by market using paid performance data before committing additional spend.',
    stats: [
      { value: '↑30%', label: 'Lead Conversions'   },
      { value: '↓40%', label: 'CPA'                 },
      { value: '×4',   label: 'Countries Expanded'  },
    ],
    bullets: [
      'Directed integrated lifecycle campaigns — content, email, and social — driving a 30% increase in lead conversions.',
      'Expanded the program internationally from Canada to Mexico, Finland, Australia, and parts of Europe.',
      'Audited all paid acquisition channels, optimising CPA by 40% through A/B testing and audience segmentation across Search, Display, and Meta Ads.',
      'Relaunched the Fertility Frontier podcast — creating 2 episodes/month and securing a full year\'s content pipeline.',
      'Led a team of 3 managing content across web, social, and podcast platforms.',
      'Grew organic acquisition by 25% via SEO-optimised web architecture and content strategies.',
    ],
    tools: ['Mailchimp', 'Meta Ads', 'SEO', 'Podcast Strategy', 'International Expansion', 'Lead Nurturing'],
    artifacts: [
      { type: 'image', src: '/artifacts/her-helping-habit/Donor Medical Benefits.png',       caption: 'Donor Medical Benefits' },
      { type: 'image', src: '/artifacts/her-helping-habit/Egg Donor.jpg',                    caption: 'Egg Donor' },
      { type: 'image', src: '/artifacts/her-helping-habit/Embryo adoption.jpg',              caption: 'Embryo Adoption' },
      { type: 'image', src: '/artifacts/her-helping-habit/LGBTQ+ community suppoty.jpg',     caption: 'LGBTQ+ Community Support' },
      { type: 'image', src: '/artifacts/her-helping-habit/Podcast launch Ig post temp.png',  caption: 'Podcast Launch — Instagram Post' },
      { type: 'video', youtubeId: 'onnHvKZdC_g', caption: 'Fertility Frontier Podcast — Episode 1' },
      { type: 'video', youtubeId: 'ZNEsBD_HKwQ', caption: 'Fertility Frontier Podcast — Episode 2' },
      { type: 'video', youtubeId: 'hJpJVaE42Wg', caption: 'Fertility Frontier Podcast — Episode 3' },
      { type: 'video', youtubeId: 'Vg9_282gFMU', caption: 'Fertility Frontier Podcast — Episode 4' },
    ],
  },
  {
    slug: 'vinn-automotive',
    company: 'VINN Automotive',
    location: 'Victoria, BC',
    period: 'Aug 2022 – Jan 2023',
    type: 'Full-Time',
    role: 'Marketing Specialist',
    description:
      'VINN Automotive is a subscription-based car dealership — a relatively new model in the Canadian market. I managed the full performance marketing stack: paid acquisition, lifecycle email, CRM, and analytics tooling. The challenge was funnel visibility — the team didn\'t have a clear picture of where users were dropping off between first touch and purchase. I integrated Close CRM with GA4, Tag Manager, and Hotjar to build a cohesive tracking layer. With drop-off data in hand, I redesigned the email retention sequences and ran paid campaigns with continuous A/B testing, lifting retention and conversion by 30%.',
    stats: [
      { value: '↑30%', label: 'Retention & Conversion' },
    ],
    bullets: [
      'Managed end-to-end lifecycle and performance marketing integrating paid, organic, and CRM channels.',
      'Integrated and optimised Close CRM, GA4, Tag Manager, and Hotjar to improve funnel visibility.',
      'Analysed drop-off data and implemented email marketing improvements boosting retention and conversion by 30%.',
      'Ran paid acquisition campaigns with ongoing A/B testing to improve marketing ROI.',
    ],
    tools: ['Close CRM', 'GA4', 'Hotjar', 'Paid Ads', 'A/B Testing', 'Tag Manager'],
    artifacts: [
      // { type: 'image', src: '/artifacts/vinn-automotive/filename.jpg', caption: 'Caption here' },
      // { type: 'pdf', driveId: 'GOOGLE_DRIVE_FILE_ID', caption: 'Caption here' },
      // { type: 'video', driveId: 'GOOGLE_DRIVE_FILE_ID', caption: 'Caption here' },
    ],
  },
  {
    slug: 'regal-immigration',
    company: 'Regal Immigration',
    location: 'Surrey, BC',
    period: 'Dec 2021 – Mar 2022',
    type: 'Full-Time',
    role: 'Marketing Coordinator',
    description:
      'Regal Immigration is a consultancy helping clients navigate Canadian immigration processes. I came in as Marketing Coordinator to strengthen their digital presence and improve how they were communicating with prospective clients online. I ran an SEO audit that surfaced several UX barriers on the site, produced social content and digital materials, and put in place a more structured content calendar to support consistent brand communication.',
    stats: [],
    bullets: [
      'Developed and executed digital communication strategies enhancing brand awareness and client acquisition.',
      'Conducted SEO audits identifying UX barriers and recommended site performance improvements.',
      'Produced social content, digital materials, and leadership reports supporting cross-functional collaboration.',
    ],
    tools: ['SEO', 'Content Strategy', 'Digital Comms', 'Analytics'],
    artifacts: [
      // { type: 'image', src: '/artifacts/regal-immigration/filename.jpg', caption: 'Caption here' },
      // { type: 'pdf', driveId: 'GOOGLE_DRIVE_FILE_ID', caption: 'Caption here' },
    ],
  },
  {
    slug: 'consultants-factory',
    company: 'Consultants Factory',
    location: 'Bangalore, India',
    period: 'Jan 2020 – Dec 2020',
    type: 'Dual Role',
    role: 'Business Manager → Marketing Intern',
    description:
      'Consultants Factory is a Bangalore-based cybersecurity IT training company. I started as a Marketing Intern and moved into a Business Manager role within the same year. The position gave me broad exposure to the full marketing mix — CRM integration, campaign management, content production across video and social, and direct stakeholder reporting. I ran Google Ads and LinkedIn Ads campaigns and advised leadership on KPI-driven strategy adjustments based on ongoing performance data.',
    stats: [],
    bullets: [
      'Led product marketing and communication initiatives — CRM integration, campaign management, and stakeholder reporting for a cybersecurity IT training company.',
      'Created digital content across video, stills, and carousels to enhance brand storytelling.',
      'Ran outreach and lead generation through targeted messaging, and advised executives on KPI-driven strategy adjustments.',
    ],
    tools: ['CRM', 'Graphic Design', 'Google Ads', 'LinkedIn Ads', 'Copywriting', 'Blog Writing'],
    artifacts: [
      { type: 'image', src: '/artifacts/consultants-factory/COBIT FULL.png',                caption: 'COBIT Full' },
      { type: 'image', src: '/artifacts/consultants-factory/cobit IMP.png',                 caption: 'COBIT Implementation' },
      { type: 'image', src: '/artifacts/consultants-factory/FIND A WAY OR FADE AWAY.png',   caption: 'Find A Way Or Fade Away' },
      { type: 'image', src: '/artifacts/consultants-factory/ITIL.png',                      caption: 'ITIL' },
      { type: 'image', src: '/artifacts/consultants-factory/ITIL2.png',                     caption: 'ITIL 2' },
      { type: 'image', src: '/artifacts/consultants-factory/Marketing Communication 1.png', caption: 'Marketing Communication' },
      { type: 'image', src: '/artifacts/consultants-factory/Oct webinar 2.png',             caption: 'October Webinar' },
      { type: 'image', src: '/artifacts/consultants-factory/oct webinar 1.png',             caption: 'October Webinar 2' },
      { type: 'image', src: '/artifacts/consultants-factory/SIAM.png',                      caption: 'SIAM' },
      { type: 'image', src: '/artifacts/consultants-factory/siam today.png',                caption: 'SIAM Today' },
      { type: 'image', src: '/artifacts/consultants-factory/course.png',                    caption: 'Course' },
      { type: 'image', src: '/artifacts/consultants-factory/foundation 21st.png',           caption: 'Foundation 21st' },
    ],
  },
];
