export const work = [
  {
    company: 'City Green Solutions',
    location: 'Victoria, BC',
    period: 'Jul 2023 – Dec 2025',
    type: 'Full-Time',
    role: 'Marketing & Customer Experience Specialist',
    stats: [
      { value: '↑25–35%', label: 'Program Engagement' },
      { value: '↓20%',   label: 'Drop-off Rate'       },
      { value: '↑15%',   label: 'Email Engagement'    },
    ],
    bullets: [
      'Planned and executed multi-channel lifecycle campaigns across email, social, and web — contributing to a 25–35% increase in program engagement.',
      'Developed and optimised customer journey touchpoints reducing user drop-offs by 20% across Instagram, LinkedIn, and YouTube.',
      'Managed CRM-driven communications via HubSpot, segmenting audiences for targeted messaging based on user behaviour and program eligibility.',
      'Designed and conducted market research and surveys for 5 municipal districts across British Columbia.',
      'Designed, branded, and executed the Retrofit Community Festival — an annual event connecting homeowners with certified contractors.',
      'Built GA4 dashboards and ran A/B tests to refine messaging, boosting engagement rates by 15%.',
    ],
    tools: ['HubSpot', 'GA4', 'Email Marketing', 'Meta Ads', 'Google Ads', 'A/B Testing', 'Event Marketing', 'Market Research'],
  },
  {
    company: 'Her Helping Habit',
    location: 'Vancouver, BC',
    period: 'Feb 2023 – Jul 2023',
    type: 'Contract',
    role: 'Marketing Lead',
    stats: [
      { value: '↑30%', label: 'Lead Conversions'    },
      { value: '↓40%', label: 'CPA'                 },
      { value: '×4',   label: 'Countries Expanded'  },
    ],
    bullets: [
      'Directed integrated lifecycle campaigns — content, email, and social — driving a 30% increase in lead conversions.',
      'Expanded the program internationally from Canada to Mexico, Finland, Australia, and parts of Europe.',
      'Audited all paid acquisition channels, optimising CPA by 40% through A/B testing and audience segmentation across Search, Display, and Meta Ads.',
      'Relaunched the Fertility Frontier podcast — creating 2 episodes/month and securing a full year\'s content pipeline.',
      'Led a team of 3 managing content across web, social, and podcast platforms.',
      'Grew organic acquisition by 25% via SEO-optimised web architecture and content strategies.',
    ],
    tools: ['Mailchimp', 'Meta Ads', 'SEO', 'Podcast Strategy', 'International Expansion', 'Lead Nurturing'],
  },
  {
    company: 'VINN Automotive',
    location: 'Victoria, BC',
    period: 'Aug 2022 – Jan 2023',
    type: 'Full-Time',
    role: 'Marketing Specialist',
    stats: [
      { value: '↑30%', label: 'Retention & Conversion' },
    ],
    bullets: [
      'Managed end-to-end lifecycle and performance marketing integrating paid, organic, and CRM channels.',
      'Integrated and optimised Close CRM, GA4, Tag Manager, and Hotjar to improve funnel visibility.',
      'Analysed drop-off data and implemented email marketing improvements boosting retention and conversion by 30%.',
      'Ran paid acquisition campaigns with ongoing A/B testing to improve marketing ROI.',
    ],
    tools: ['Close CRM', 'GA4', 'Hotjar', 'Paid Ads', 'A/B Testing', 'Tag Manager'],
  },
  {
    company: 'Regal Immigration',
    location: 'Surrey, BC',
    period: 'Dec 2021 – Mar 2022',
    type: 'Full-Time',
    role: 'Marketing Coordinator',
    stats: [],
    bullets: [
      'Developed and executed digital communication strategies enhancing brand awareness and client acquisition.',
      'Conducted SEO audits identifying UX barriers and recommended site performance improvements.',
      'Produced social content, digital materials, and leadership reports supporting cross-functional collaboration.',
    ],
    tools: ['SEO', 'Content Strategy', 'Digital Comms', 'Analytics'],
  },
  {
    company: 'Consultants Factory',
    location: 'Bangalore, India',
    period: 'Jan 2020 – Dec 2020',
    type: 'Dual Role',
    role: 'Business Manager → Marketing Intern',
    stats: [],
    bullets: [
      'Led product marketing and communication initiatives — CRM integration, campaign management, and stakeholder reporting for a cybersecurity IT training company.',
      'Created digital content across video, stills, and carousels to enhance brand storytelling.',
      'Ran outreach and lead generation through targeted messaging, and advised executives on KPI-driven strategy adjustments.',
    ],
    tools: ['CRM', 'Graphic Design', 'Google Ads', 'LinkedIn Ads', 'Copywriting', 'Blog Writing'],
  },
];
